---
title: Visual Rock Paper Scissors
hero_image: images/banner.png
description:
version: 4
listed: true
copyedit: true
last_tested: '2018-12-06'
steps:
- title: Introduction
  completion: engaged
- title: Make the building blocks of the game
- title: Set up the rules of the game
- title: Set up scorekeeping
- title: Clean your code
  completion: internal
- title: Create an interface
