title: c3-wolfram-rock-paper-scissors
hero_image: images/banner.png
description: c3-wolfram-rock-paper-scissors description
version: 4
listed: false
copyedit: false
last_tested: "2019-01-31"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
